import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';

const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'msedge' });
const errors = [];
const report = {};
await mkdir('.qa/screenshots', { recursive: true });
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  page.setDefaultTimeout(15000);
  page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:5174');
  const chooser = page.waitForEvent('filechooser'); await page.locator('.topbar [data-action=import]').click();
  const wav = Buffer.alloc(44 + 8000 * 120 * 2);
  wav.write('RIFF'); wav.writeUInt32LE(wav.length - 8, 4); wav.write('WAVEfmt ', 8); wav.writeUInt32LE(16, 16); wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22); wav.writeUInt32LE(8000, 24); wav.writeUInt32LE(16000, 28); wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34); wav.write('data', 36); wav.writeUInt32LE(wav.length - 44, 40);
  await (await chooser).setFiles(['Alfa', 'Beta', 'Gama'].map(name => ({ name: `${name}.wav`, mimeType: 'audio/wav', buffer: wav })));
  await page.waitForFunction(() => document.querySelectorAll('#filtered-list .track').length === 3);
  console.log('Imported fixtures');
  await page.evaluate(async () => {
    const records = await new Promise((resolve, reject) => {
      const open = indexedDB.open('fluxo-mobile-offline'); open.onerror = () => reject(open.error);
      open.onsuccess = () => {
        const db = open.result, tx = db.transaction('downloads', 'readwrite'), store = tx.objectStore('downloads'), read = store.getAll();
        read.onsuccess = () => { for (const record of read.result) { record.meta.url = `https://audio.example.invalid/${record.meta.title}.wav`; store.put(record); } };
        tx.oncomplete = () => { db.close(); resolve(read.result); };
        tx.onerror = () => { db.close(); reject(tx.error); };
      };
    });
    const local = records.map(record => ({ ...record.meta, id: `alias-${record.meta.title}`, url: `https://audio.example.invalid/${record.meta.title}.wav` }));
    const extra = Array.from({ length: 180 }, (_, i) => ({ id: `extra-${i}`, title: `Memória ${String(i).padStart(3, '0')}`, artist: i % 2 ? 'Artista um' : 'Artista dois', url: `https://example.invalid/${i}.mp3`, duration: 120 }));
    localStorage.fluxo_mobile_v2 = JSON.stringify({ library: [...local, ...extra], favorites: [], history: extra.slice(0, 35), playlists: [{ id: 'base', title: 'Dia a dia', tracks: local, offlineOnly: true }, { id: 'second', title: 'Treino', tracks: [], offlineOnly: true }], settings: { autoDownload: false, offline: true } });
  });
  await page.reload();
  console.log('Seeded library');
  await page.getByRole('tab', { name: 'Salvas', exact: true }).click();
  await page.getByRole('button', { name: 'Selecionar músicas', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Filtrar músicas', exact: true }).fill('Beta');
  await page.getByRole('checkbox', { name: 'Selecionar todas as 1 músicas filtradas', exact: true }).check();
  await page.getByRole('searchbox', { name: 'Filtrar músicas', exact: true }).fill('');
  assert.equal(await page.locator('.bulk-heading strong').textContent(), '1 selecionadas');
  await page.getByRole('checkbox', { name: 'Selecionar Alfa', exact: true }).check();
  assert.equal(await page.locator('.bulk-heading strong').textContent(), '2 selecionadas');
  await page.getByRole('button', { name: 'Adicionar selecionadas a uma playlist', exact: true }).click();
  await page.getByRole('button', { name: 'Criar playlist com a seleção', exact: true }).click();
  await page.getByRole('textbox', { name: 'Nome da playlist', exact: true }).fill('Minha seleção');
  await page.getByRole('button', { name: 'Salvar playlist', exact: true }).click();
  assert.equal(await page.locator('#filtered-list .track').count(), 2); report.bulkPlaylist = true;
  console.log('Created bulk playlist');
  await page.getByRole('button', { name: 'Opções da playlist', exact: true }).click();
  await page.getByRole('button', { name: 'Fixar playlist', exact: true }).click();
  await page.getByRole('button', { name: 'Voltar à biblioteca', exact: true }).click();
  await page.getByRole('tab', { name: 'Coleções', exact: true }).click();
  assert.match(await page.locator('.playlist-card').first().textContent(), /Minha seleção/); report.pinned = true;
  await page.locator('.playlist-card').first().click();
  await page.getByRole('button', { name: 'Selecionar músicas', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Selecionar Alfa', exact: true }).check();
  await page.getByRole('button', { name: 'Mais ações da seleção', exact: true }).click();
  await page.getByRole('button', { name: 'Remover da playlist', exact: true }).click();
  await page.getByRole('button', { name: 'Confirmar', exact: true }).click();
  assert.equal(await page.locator('#filtered-list .track').count(), 1);
  await page.getByRole('button', { name: 'Desfazer', exact: true }).click();
  assert.equal(await page.locator('#filtered-list .track').count(), 2); report.bulkRemovalUndo = true;
  await page.getByRole('button', { name: 'Selecionar músicas', exact: true }).click();
  await page.getByRole('checkbox', { name: 'Selecionar todas as 2 músicas filtradas', exact: true }).check();
  await page.getByRole('button', { name: 'Favoritar selecionadas', exact: true }).click();
  assert.equal(await page.evaluate(() => JSON.parse(localStorage.fluxo_mobile_v2).favorites.length), 2); report.bulkFavorite = true;
  await page.getByRole('searchbox', { name: 'Filtrar músicas', exact: true }).fill('Beta');
  await page.getByRole('button', { name: 'Tocar esta seleção', exact: true }).click();
  await page.locator('#mini [data-action=toggle][aria-label=Pausar]').waitFor();
  assert.match(await page.locator('#mini .track-copy strong').textContent(), /Beta/); report.cachedAliasPlayback = true;
  console.log('Cached alias is playing');
  const append = track => page.evaluate(async track => { const { commands } = await import('./platform.js'); await commands.append({ track }); }, track);
  const tracks = await page.evaluate(() => JSON.parse(localStorage.fluxo_mobile_v2).library.slice(0, 3));
  const beta = tracks.find(track => track.title === 'Beta'), gama = tracks.find(track => track.title === 'Gama');
  await page.locator('.navigation [data-tab=queue]').click();
  await append(beta); await append(gama); await append(beta);
  await page.waitForFunction(() => document.querySelectorAll('[data-queue-index]').length === 4);
  console.log('Queue updated after append');
  assert.equal(await page.locator('[data-queue-index].playing').count(), 1); report.duplicateQueueHighlight = true;
  await page.locator('#mini [data-action=toggle]').click();
  await page.getByRole('button', { name: 'Abrir player', exact: true }).click();
  await page.locator('#seek').evaluate(input => { input.value = '35'; input.dispatchEvent(new Event('change', { bubbles: true })); });
  await page.waitForTimeout(300); await page.getByRole('button', { name: 'Voltar 10 segundos', exact: true }).click();
  await page.waitForTimeout(300); assert.ok(Math.abs(Number(await page.locator('#seek').inputValue()) - 25) < 1);
  await page.getByRole('button', { name: 'Avançar 10 segundos', exact: true }).click();
  await page.waitForTimeout(300); assert.ok(Math.abs(Number(await page.locator('#seek').inputValue()) - 35) < 1); report.seekSteps = true;
  await page.getByRole('button', { name: 'Minimizar player', exact: true }).click();
  await page.getByRole('button', { name: 'Organizar fila', exact: true }).click();
  await page.getByRole('button', { name: 'Remover repetidas a seguir', exact: true }).click();
  assert.equal(await page.locator('[data-queue-index]').count(), 2);
  assert.equal(await page.locator('#mini [data-action=toggle]').getAttribute('aria-label'), 'Reproduzir'); report.queueCleanupPreservesPause = true;
  await page.locator('[data-queue-index="0"] [data-action=track-menu]').click();
  await page.getByRole('button', { name: 'Remover da fila', exact: true }).click();
  await page.waitForTimeout(300);
  assert.equal(await page.locator('#mini [data-action=toggle]').getAttribute('aria-label'), 'Reproduzir'); report.pausedRemoval = true;
  await page.locator('[data-queue-index="0"] [data-action=track-menu]').click();
  await page.getByRole('button', { name: 'Remover da fila', exact: true }).click();
  assert.equal(await page.locator('#mini').isHidden(), true); report.emptyQueueReset = true;
  await page.locator('.navigation [data-tab=library]').click();
  await page.getByRole('button', { name: 'Voltar à biblioteca', exact: true }).click();
  await page.getByRole('tab', { name: 'Coleções', exact: true }).click();
  await page.getByRole('button', { name: 'Ver histórico completo', exact: true }).click();
  assert.ok(await page.locator('#filtered-list .track').count() > 8);
  await page.getByRole('searchbox', { name: 'Filtrar músicas', exact: true }).fill('Memória 01');
  assert.equal(await page.locator('#filtered-list .track').count(), 10);
  await page.getByRole('button', { name: 'Limpar histórico', exact: true }).click();
  await page.getByRole('button', { name: 'Confirmar', exact: true }).click();
  await page.getByRole('button', { name: 'Desfazer', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Filtrar músicas', exact: true }).fill('');
  assert.ok(await page.locator('#filtered-list .track').count() >= 35); report.history = true;
  await page.getByRole('button', { name: 'Voltar às coleções', exact: true }).click();
  await page.getByRole('tab', { name: 'Salvas', exact: true }).click();
  await page.getByRole('searchbox', { name: 'Filtrar músicas', exact: true }).fill('');
  await page.getByRole('button', { name: 'Carregar mais músicas', exact: true }).click();
  await page.evaluate(() => scrollTo(0, 1600));
  const y = await page.evaluate(() => scrollY);
  await page.locator('.navigation [data-tab=search]').click();
  await page.getByRole('heading', { name: 'Buscar', exact: true }).waitFor();
  await page.locator('.navigation [data-tab=library]').click();
  await page.waitForFunction(() => document.querySelectorAll('#filtered-list .track').length === 160);
  console.log('Scroll restoration', { expected: y, actual: await page.evaluate(() => scrollY) });
  await page.waitForFunction(expected => Math.abs(scrollY - expected) < 2, y, { timeout: 3000 });
  assert.equal(await page.locator('#filtered-list .track').count(), 160); report.navigationRestoresScrollAndPagination = true;
  for (const width of [320, 390, 820]) {
    await page.setViewportSize({ width, height: width === 320 ? 640 : 844 });
    await page.getByRole('tab', { name: 'Coleções', exact: true }).click();
    await page.evaluate(() => scrollTo(0, 0));
    await page.screenshot({ path: `.qa/screenshots/collections-2.5-${width}.png`, fullPage: true });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.getByRole('tab', { name: 'Salvas', exact: true }).click();
    await page.getByRole('button', { name: 'Selecionar músicas', exact: true }).click();
    await page.getByRole('checkbox', { name: 'Selecionar todas as 183 músicas filtradas', exact: true }).check();
    assert.equal(await page.locator('.bulk-heading strong').textContent(), '183 selecionadas', 'Select all applies to the filtered collection, not only the first page');
    await page.evaluate(() => scrollTo(0, 0));
    await page.screenshot({ path: `.qa/screenshots/bulk-2.5-${width}.png` });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    assert.equal(await page.evaluate(() => fluxoBack()), true);
    assert.equal(await page.locator('.bulk-toolbar').count(), 0);
  }
  assert.deepEqual(errors, []);
  await writeFile('.qa/collections-ui-report.json', JSON.stringify(report, null, 2)); console.log(report);
} finally { await browser.close(); }
