import { chromium } from 'playwright';
import assert from 'node:assert/strict';
import { mkdir, writeFile } from 'node:fs/promises';

const browser = await chromium.launch({ headless: true, channel: process.env.BROWSER_CHANNEL || 'msedge' });
const errors = [], report = {};
await mkdir('.qa/screenshots', { recursive: true });
try {
  const page = await browser.newPage({ viewport: { width: 390, height: 844 } });
  await page.context().grantPermissions(['clipboard-read', 'clipboard-write']);
  page.setDefaultTimeout(12000); page.on('pageerror', error => errors.push(error.message));
  await page.goto(process.env.TEST_URL || 'http://127.0.0.1:5174');
  const wav = Buffer.alloc(44 + 8000 * 90 * 2);
  wav.write('RIFF'); wav.writeUInt32LE(wav.length - 8, 4); wav.write('WAVEfmt ', 8); wav.writeUInt32LE(16, 16); wav.writeUInt16LE(1, 20); wav.writeUInt16LE(1, 22); wav.writeUInt32LE(8000, 24); wav.writeUInt32LE(16000, 28); wav.writeUInt16LE(2, 32); wav.writeUInt16LE(16, 34); wav.write('data', 36); wav.writeUInt32LE(wav.length - 44, 40);
  const choose = page.waitForEvent('filechooser'); await page.locator('.topbar [data-action=import]').click();
  await (await choose).setFiles(['Alfa', 'Beta', 'Gama'].map(name => ({ name: `${name}.wav`, mimeType: 'audio/wav', buffer: wav })));
  await page.waitForFunction(() => document.querySelectorAll('#filtered-list .track').length === 3);
  await page.evaluate(async () => {
    const { commands } = await import('./platform.js');
    const tracks = (await commands.downloads()).map((track, i) => ({ ...track, id: `alias-${i}`, artist: i < 2 ? 'Álvaro & Banda' : 'Outra artista', duration: 90, url: `https://example.invalid/${i}.wav` }));
    await new Promise((resolve, reject) => {
      const request = indexedDB.open('fluxo-mobile-offline');
      request.onsuccess = () => { const db = request.result, tx = db.transaction('downloads', 'readwrite'), store = tx.objectStore('downloads'), read = store.getAll(); read.onsuccess = () => read.result.forEach((record, i) => { Object.assign(record.meta, { ...tracks[i], id: record.id }); store.put(record); }); tx.oncomplete = () => { db.close(); resolve(); }; tx.onerror = () => reject(tx.error); };
    });
    localStorage.fluxo_mobile_v2 = JSON.stringify({ library: tracks, favorites: [tracks[0]], playlists: [{ id: 'base', title: 'Meus dias de música', tracks, offlineOnly: true, pinned: true }], settings: { autoDownload: false } });
  });
  await page.reload();
  await page.getByRole('button', { name: /Artistas.*biblioteca/ }).click();
  assert.equal(await page.locator('.artist-row').count(), 2);
  await page.getByRole('searchbox', { name: 'Buscar artistas', exact: true }).fill('ALVARO');
  assert.equal(await page.locator('.artist-row').count(), 1);
  await page.locator('.artist-row').click();
  assert.equal(await page.locator('#filtered-list .track').count(), 2);
  assert.match(await page.locator('.artist-heading').textContent(), /2 disponíveis offline/);
  report.artistAliasesAndSearch = true;
  await page.getByRole('button', { name: 'Tocar esta seleção', exact: true }).click();
  await page.locator('#mini [aria-label=Pausar]').waitFor();
  await page.getByRole('button', { name: 'Criar playlist deste artista', exact: true }).click();
  assert.equal(await page.getByRole('textbox', { name: 'Nome da playlist', exact: true }).inputValue(), 'Álvaro & Banda');
  await page.getByRole('button', { name: 'Salvar playlist', exact: true }).click();
  assert.equal(await page.locator('#filtered-list .track').count(), 2); report.artistPlaylistAndPlayback = true;
  await page.locator('#filtered-list [data-action=track-menu]').first().click();
  assert.equal(await page.locator('.menu-section[open]').count(), 1);
  await page.getByRole('button', { name: 'Informações da música', exact: true }).click();
  assert.match(await page.locator('.track-facts').textContent(), /Pronta para ouvir offline/);
  assert.match(await page.locator('.track-facts').textContent(), /MB/);
  await page.getByRole('button', { name: 'Copiar link da música', exact: true }).click();
  await page.waitForFunction(() => document.querySelector('#toast').textContent.includes('Link copiado'));
  assert.match(await page.locator('#toast').textContent(), /Link copiado/); report.trackInformationAndClipboard = true;
  await page.getByRole('button', { name: 'Fechar', exact: true }).click();
  await page.locator('.navigation [data-tab=queue]').click();
  await page.locator('[data-queue-index="1"] [data-action=track-menu]').click();
  await page.evaluate(async () => { const { commands } = await import('./platform.js'); await commands.append({ track: { id: 'changed', title: 'Fila alterada', url: '' } }); });
  await page.getByRole('button', { name: 'Remover da fila', exact: true }).click();
  assert.match(await page.locator('#toast').textContent(), /lista mudou/i);
  assert.equal(await page.locator('[data-queue-index]').count(), 3); report.staleMenuProtection = true;
  await page.getByRole('button', { name: 'Abrir player', exact: true }).click();
  await page.getByRole('button', { name: 'Timer', exact: true }).click();
  await page.getByRole('button', { name: '15 minutos', exact: true }).click();
  assert.match(await page.locator('[data-sleep-label]').textContent(), /14:5\d/);
  assert.match(await page.locator('.player-context').textContent(), /No dispositivo.*1 de 3/); report.playerContextAndCountdown = true;
  await page.getByRole('button', { name: 'Minimizar player', exact: true }).click();
  await page.locator('.navigation [data-tab=search]').click();
  await page.evaluate(async () => {
    const { commands } = await import('./platform.js'); window.searchCalls = [];
    commands.search = async query => { window.searchCalls.push(query); await new Promise(resolve => setTimeout(resolve, query === 'lenta' ? 1800 : 100)); return [{ id: query + '-a', title: 'Curta ' + query, artist: 'Banda', duration: 120, url: 'https://example.invalid/' + query + '/a' }, { id: query + '-b', title: 'Longa ' + query, artist: 'Banda', duration: 300, url: 'https://example.invalid/' + query + '/b' }]; };
  });
  const search = async query => { await page.getByRole('searchbox', { name: 'Buscar músicas', exact: true }).fill(query); await page.getByRole('button', { name: 'Pesquisar', exact: true }).click(); };
  await search('teste'); await page.getByRole('button', { name: 'Tocar Curta teste', exact: true }).waitFor();
  await page.getByRole('combobox', { name: 'Filtrar resultados', exact: true }).selectOption('long');
  assert.equal(await page.locator('#view .track').count(), 1);
  await search('teste'); assert.equal(await page.evaluate(() => searchCalls.length), 1);
  assert.match(await page.locator('.search-sources').textContent(), /Busca recente/);
  await page.getByRole('button', { name: 'Atualizar resultados', exact: true }).click();
  await page.getByRole('button', { name: 'Tocar Longa teste', exact: true }).waitFor();
  assert.equal(await page.evaluate(() => searchCalls.length), 2); report.searchCacheRefreshAndFilters = true;
  await page.getByRole('combobox', { name: 'Filtrar resultados', exact: true }).selectOption('downloaded');
  assert.equal(await page.locator('#view .track').count(), 0);
  await page.evaluate(async () => {
    const { commands } = await import('./platform.js'); const downloads = commands.downloads.bind(commands);
    commands.downloads = async () => [...await downloads(), { id: 'teste-b', title: 'Longa teste', artist: 'Banda', duration: 300, url: 'https://example.invalid/teste/b', status: 'ready', bytes: 1000 }];
  });
  await page.getByRole('button', { name: 'Tocar Longa teste', exact: true }).waitFor(); report.downloadFilterRefreshesOnCompletion = true;
  await page.getByRole('combobox', { name: 'Filtrar resultados', exact: true }).selectOption('long');
  await search('lenta'); await page.getByRole('button', { name: 'Cancelar busca', exact: true }).click();
  await search('nova'); await page.getByRole('button', { name: 'Tocar Longa nova', exact: true }).waitFor();
  await page.waitForTimeout(1900);
  assert.equal(await page.getByRole('button', { name: 'Tocar Longa lenta', exact: true }).count(), 0); report.cancelDoesNotBlockNextSearch = true;
  await page.getByRole('searchbox', { name: 'Buscar músicas', exact: true }).fill('rascunho preservado');
  await page.evaluate(() => window.dispatchEvent(new Event('online')));
  assert.equal(await page.getByRole('searchbox', { name: 'Buscar músicas', exact: true }).inputValue(), 'rascunho preservado'); report.searchDraftSurvivesRender = true;
  for (const viewport of [{ width: 320, height: 640 }, { width: 390, height: 844 }, { width: 820, height: 1180 }]) {
    await page.setViewportSize(viewport);
    await page.locator('.navigation [data-tab=library]').click();
    await page.getByRole('button', { name: 'Voltar à biblioteca', exact: true }).click();
    if (await page.getByRole('button', { name: 'Voltar aos artistas', exact: true }).count()) await page.getByRole('button', { name: 'Voltar aos artistas', exact: true }).click();
    if (await page.getByRole('button', { name: 'Voltar às coleções', exact: true }).count()) await page.getByRole('button', { name: 'Voltar às coleções', exact: true }).click();
    await page.getByRole('tab', { name: 'Coleções', exact: true }).click();
    await page.evaluate(() => scrollTo(0, 0));
    await page.screenshot({ path: `.qa/screenshots/professional-home-${viewport.width}.png`, fullPage: true });
    assert.equal(await page.evaluate(() => document.documentElement.scrollWidth > innerWidth), false);
    await page.getByRole('button', { name: /Artistas.*biblioteca/ }).click();
    await page.getByRole('searchbox', { name: 'Buscar artistas', exact: true }).fill('');
    await page.screenshot({ path: `.qa/screenshots/professional-artists-${viewport.width}.png`, fullPage: true });
    await page.getByRole('button', { name: 'Voltar às coleções', exact: true }).click();
    await page.getByRole('button', { name: 'Abrir player', exact: true }).click();
    await page.waitForTimeout(250);
    await page.screenshot({ path: `.qa/screenshots/professional-player-${viewport.width}.png` });
    const bottom = await page.locator('.player-footer').evaluate(el => el.getBoundingClientRect().bottom);
    console.log('Player layout', viewport, bottom); assert.ok(bottom <= viewport.height + 1);
    await page.getByRole('button', { name: 'Minimizar player', exact: true }).click();
    await page.locator('.playlist-card').first().click();
  }
  assert.deepEqual(errors, []); report.responsive = true;
  await writeFile('.qa/professional-ui-report.json', JSON.stringify(report, null, 2)); console.log(report);
} finally { await browser.close(); }
